apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbapi
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: prod
  source:
    path: prod/dbapi
    repoURL: 'https://github.com/project-for-good/argocd.git'
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: null
