apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-subchart
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: cert-manager
  source:
    path: cert-manager
    repoURL: 'https://github.com/project-for-good/argocd.git'
    targetRevision: develop
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: null
