apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: ingress-nginx
  source:
    path: ingress-nginx
    repoURL: 'https://github.com/project-for-good/argocd.git'
    targetRevision: develop
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: null
